[default]
prefix = "Tux"

[daemon]
audio_capture_enabled = false
audio_device = "default"

[whisper]
model = "base.en"

[shell]
type = "zsh"

[actions]
open = "i3-msg exec"
close = "pkill"

[commands]
browser = "google-chrome-stable"
terminal = "kitty"